CREATE TABLE IF NOT EXISTS berufe (
  id INT AUTO_INCREMENT PRIMARY KEY,
  beruf VARCHAR(255) NOT NULL
);

INSERT INTO berufe (beruf) VALUES
('Altenpfleger/in'),
('Anlagenmechaniker/in für Sanitär-, Heizungs- und Klimatechnik'),
('Architekt/in'),
('Augenoptiker/in'),
('Bankkaufmann/-frau'),
('Bauingenieur/in'),
('Bauzeichner/in'),
('Betriebswirt/in'),
('Bodenleger/in'),
('Buchhalter/in'),
('Chemikant/in'),
('Chemielaborant/in'),
('Dachdecker/in'),
('Datenschutzbeauftragte/r'),
('Diplom-Finanzwirt/in'),
('Drogist/in'),
('E-Commerce-Kaufmann/-frau'),
('Energieberater/in'),
('Ergotherapeut/in'),
('Erzieher/in'),
('Fachinformatiker/in'),
('Fahrzeuglackierer/in'),
('Fertigungsmechaniker/in'),
('Finanzberater/in'),
('Fliesen-, Platten- und Mosaikleger/in'),
('Florist/in'),
('Fotograf/in'),
('Friseur/in'),
('Gebäudereiniger/in'),
('Gärtner/in'),
('Gesundheits- und Krankenpfleger/in'),
('Grafikdesigner/in'),
('Groß- und Außenhandelskaufmann/-frau'),
('Hausmeister/in'),
('Heilerziehungspfleger/in'),
('Hotelkaufmann/-frau'),
('Hotelfachmann/-frau'),
('Immobilienkaufmann/-frau'),
('Industriemechaniker/in'),
('Informatikkaufmann/-frau'),
('Ingenieur/in'),
('IT-System-Elektroniker/in'),
('Kälteanlagenbauer/in'),
('Karosserie- und Fahrzeugbaumechaniker/in'),
('Kaufmann/-frau für Büromanagement'),
('Kaufmann/-frau im Einzelhandel'),
('Kfz-Mechatroniker/in'),
('Koch/Köchin'),
('Krankenhausmanager/in'),
('Landschaftsarchitekt/in'),
('Logopäde/Logopädin'),
('Maler/in und Lackierer/in'),
('Marketingmanager/in'),
('Maschinenbauingenieur/in'),
('Maurer/in'),
('Mediengestalter/in'),
('Medizinisch-technische/r Assistent/in'),
('Mechatroniker/in'),
('Notarfachangestellte/r'),
('Operationstechnische/r Assistent/in'),
('Pflegefachmann/-frau'),
('Pharmazeutisch-technische/r Assistent/in'),
('Physiotherapeut/in'),
('Polizist/in'),
('Produktdesigner/in'),
('Programmierer/in'),
('Rechtsanwaltsfachangestellte/r'),
('Reinigungskraft'),
('Sanitärinstallateur/in'),
('Sozialarbeiter/in'),
('Speditionskaufmann/-frau'),
('Steuerfachangestellte/r'),
('Systemadministrator/in'),
('Tiefbaufacharbeiter/in'),
('Tiermedizinische/r Fachangestellte/r'),
('Tischler/in'),
('Verkäufer/in'),
('Versicherungskaufmann/-frau'),
('Verwaltungsfachangestellte/r'),
('Wirtschaftsingenieur/in'),
('Zahnarzthelfer/in'),
('Zerspanungsmechaniker/in');

-- Du kannst weitere Berufe bei Bedarf ergänzen.
